import { useState } from 'react'
import { ethers } from 'ethers'
import { VERIDOC_ABI, CONTRACT_ADDRESS } from '../config'

const SummaryCard = ({ result, wallet, showToast }) => {
  const [storing, setStoring] = useState(false)
  const [stored, setStored] = useState(false)
  const [txHash, setTxHash] = useState(null)
  const [copied, setCopied] = useState(null)

  const copyText = (text, key) => {
    navigator.clipboard.writeText(text)
    setCopied(key)
    setTimeout(() => setCopied(null), 2000)
  }

  const storeOnChain = async () => {
    if (!wallet) {
      showToast('Please connect your wallet first!', 'error')
      return
    }
    setStoring(true)
    try {
      const contract = new ethers.Contract(CONTRACT_ADDRESS, VERIDOC_ABI, wallet.signer)
      const tx = await contract.storeDocHash(result.ipfsHash)
      showToast('Transaction submitted! Waiting for confirmation...', 'info')
      await tx.wait()
      setTxHash(tx.hash)
      setStored(true)
      showToast('Document stored on blockchain! ✅', 'success')
    } catch (err) {
      const msg = err?.reason || err?.message || 'Transaction failed'
      showToast(msg.includes('already exists') ? 'This document is already stored on-chain.' : `Error: ${msg}`, 'error')
    } finally {
      setStoring(false)
    }
  }

  return (
    <div style={styles.card} className="fade-in">
      {/* Header */}
      <div style={styles.header}>
        <div style={styles.headerLeft}>
          <div style={styles.aiIcon}>
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
              <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </div>
          <div>
            <h3 style={styles.title}>AI Document Summary</h3>
            <p style={styles.subtitle}>Generated by Gemini 2.5 Flash</p>
          </div>
        </div>
        <span className="tag tag-pink">AI Analyzed</span>
      </div>

      <div style={styles.divider} />

      {/* Summary Text */}
      <div style={styles.summaryBox}>
        <p style={styles.summaryText}>{result.summary}</p>
      </div>

      <div style={styles.divider} />

      {/* IPFS Info */}
      <div>
        <p style={styles.label}>IPFS Content ID (CID)</p>
        <div style={styles.hashRow}>
          <code style={styles.hash}>{result.ipfsHash}</code>
          <button
            className="btn btn-sm btn-secondary"
            onClick={() => copyText(result.ipfsHash, 'cid')}
            title="Copy CID"
            id="copy-cid-btn"
          >
            {copied === 'cid' ? (
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
                <polyline points="20 6 9 17 4 12" stroke="var(--success)" strokeWidth="2.5" strokeLinecap="round"/>
              </svg>
            ) : (
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
                <rect x="9" y="9" width="13" height="13" rx="2" ry="2" stroke="currentColor" strokeWidth="2"/>
                <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" stroke="currentColor" strokeWidth="2"/>
              </svg>
            )}
          </button>
          {result.ipfsUrl && (
            <a
              href={result.ipfsUrl}
              target="_blank"
              rel="noreferrer"
              className="btn btn-sm btn-secondary"
              title="View on IPFS"
              id="view-ipfs-link"
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
                <path d="M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
                <polyline points="15 3 21 3 21 9" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
                <line x1="10" y1="14" x2="21" y2="3" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
              </svg>
              IPFS
            </a>
          )}
        </div>
        <p style={styles.hashNote}>This unique hash identifies your document on IPFS. Store it on-chain to create a permanent, verifiable record.</p>
      </div>

      <div style={styles.divider} />

      {/* Store on Chain Button */}
      {stored ? (
        <div style={styles.successBanner}>
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none">
            <path d="M22 11.08V12a10 10 0 11-5.93-9.14" stroke="var(--success)" strokeWidth="2.5"/>
            <polyline points="22 4 12 14.01 9 11.01" stroke="var(--success)" strokeWidth="2.5" strokeLinecap="round"/>
          </svg>
          <div>
            <p style={styles.successTitle}>Stored on Blockchain!</p>
            {txHash && (
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <code style={styles.txHash}>Tx: {txHash.slice(0, 20)}...</code>
                <button
                  className="btn btn-sm"
                  style={{ padding: '2px 8px', color: 'var(--text-secondary)', background: 'transparent', border: 'none' }}
                  onClick={() => copyText(txHash, 'tx')}
                >{copied === 'tx' ? '✓ Copied' : 'Copy'}</button>
              </div>
            )}
          </div>
        </div>
      ) : (
        <button
          className="btn btn-outline-pink"
          style={{ width: '100%' }}
          onClick={storeOnChain}
          disabled={storing}
          id="store-on-chain-btn"
        >
          {storing ? (
            <><span className="spinner" style={{ borderTopColor: 'var(--pink)' }} /> Submitting transaction...</>
          ) : (
            <>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
                <rect x="3" y="11" width="18" height="11" rx="2" ry="2" stroke="currentColor" strokeWidth="2"/>
                <path d="M7 11V7a5 5 0 0110 0v4" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
              </svg>
              Store Hash on Blockchain
            </>
          )}
        </button>
      )}
    </div>
  )
}

const styles = {
  card: {
    background: 'var(--gradient-card)',
    border: '1px solid var(--border-pink)',
    borderRadius: 'var(--radius-lg)',
    padding: '28px',
    boxShadow: 'var(--shadow-pink)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '12px',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
  },
  aiIcon: {
    width: '40px',
    height: '40px',
    background: 'var(--gradient-pink)',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    boxShadow: '0 4px 14px rgba(232, 121, 160, 0.4)',
  },
  title: {
    fontSize: '1rem',
    fontWeight: 700,
    color: 'var(--text-primary)',
  },
  subtitle: {
    fontSize: '0.75rem',
    color: 'var(--text-secondary)',
    marginTop: '2px',
  },
  divider: {
    height: '1px',
    background: 'var(--border)',
    margin: '20px 0',
  },
  summaryBox: {
    background: 'var(--bg-glass)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-md)',
    padding: '20px',
    maxHeight: '220px',
    overflowY: 'auto',
  },
  summaryText: {
    fontSize: '0.9rem',
    color: 'var(--text-primary)',
    lineHeight: 1.8,
    whiteSpace: 'pre-wrap',
  },
  label: {
    fontSize: '0.75rem',
    fontWeight: 600,
    color: 'var(--text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    marginBottom: '10px',
  },
  hashRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
  },
  hash: {
    flex: 1,
    fontSize: '0.75rem',
    color: 'var(--pink)',
    background: 'var(--pink-light)',
    padding: '8px 12px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--pink-border)',
    wordBreak: 'break-all',
    fontFamily: 'monospace',
  },
  hashNote: {
    fontSize: '0.75rem',
    color: 'var(--text-muted)',
    marginTop: '8px',
    lineHeight: 1.6,
  },
  successBanner: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '14px',
    background: 'var(--success-bg)',
    border: '1px solid rgba(74, 222, 128, 0.2)',
    borderRadius: 'var(--radius-md)',
    padding: '16px 20px',
  },
  successTitle: {
    fontWeight: 600,
    color: 'var(--success)',
    fontSize: '0.9rem',
  },
  txHash: {
    fontSize: '0.75rem',
    color: 'var(--text-secondary)',
    fontFamily: 'monospace',
  },
}

export default SummaryCard
